# Generated by Django 5.2.6 on 2025-10-13 05:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('uploaded_image', models.ImageField(blank=True, null=True, upload_to='collection_uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('suggested_themes', models.JSONField(blank=True, default=list)),
                ('suggested_backgrounds', models.JSONField(blank=True, default=list)),
                ('suggested_poses', models.JSONField(blank=True, default=list)),
                ('suggested_locations', models.JSONField(blank=True, default=list)),
                ('suggested_colors', models.JSONField(blank=True, default=list)),
                ('selected_themes', models.JSONField(blank=True, default=list)),
                ('selected_backgrounds', models.JSONField(blank=True, default=list)),
                ('selected_poses', models.JSONField(blank=True, default=list)),
                ('selected_locations', models.JSONField(blank=True, default=list)),
                ('selected_colors', models.JSONField(blank=True, default=list)),
                ('final_moodboard_prompt', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='generated_moodboards/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_images', to='probackendapp.collection')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('about', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='probackendapp.project'),
        ),
    ]
