# Generated by Django 5.2.6 on 2025-10-13 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probackendapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
    ]
