# Generated by Django 5.2.6 on 2025-10-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('probackendapp', '0002_remove_project_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='moodboard_explanation',
            field=models.TextField(blank=True),
        ),
    ]
