# Generated by Django 5.2.6 on 2025-10-21 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('probackendapp', '0003_collection_moodboard_explanation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collection',
            name='project',
        ),
        migrations.RemoveField(
            model_name='generatedimage',
            name='collection',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Collection',
        ),
        migrations.DeleteModel(
            name='GeneratedImage',
        ),
    ]
