# Generated by Django 5.2.6 on 2025-09-23 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ornament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ornaments/')),
                ('prompt', models.CharField(max_length=255)),
                ('generated_image', models.ImageField(blank=True, null=True, upload_to='generated/')),
            ],
        ),
    ]
