# Generated by Django 5.2.6 on 2025-10-08 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgbackendapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornament',
            name='image',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
