# Generated by Django 5.2.6 on 2025-10-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imgbackendapp', '0002_alter_ornament_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ornament',
            name='prompt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
